//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.SiparisIcerigi = new HashSet<SiparisIcerigi>();
        }
    
        public int kitapNo { get; set; }
        public int yazarNo { get; set; }
        public string baslik { get; set; }
        public Nullable<int> sayfaSayisi { get; set; }
        public string basimTarihi { get; set; }
        public string tur { get; set; }
        public Nullable<double> fiyat { get; set; }
        public Nullable<int> stokSayisi { get; set; }
        public string gorselURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisIcerigi> SiparisIcerigi { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
