//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SiparisIcerigi = new HashSet<SiparisIcerigi>();
        }
    
        public int siparisNo { get; set; }
        public int siparisVeren { get; set; }
        public int teslimatAdresi { get; set; }
        public System.DateTime siparisTarihi { get; set; }
        public Nullable<double> siparisTutari { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisIcerigi> SiparisIcerigi { get; set; }
    }
}
