//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookstoreWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisIcerigi
    {
        public int ID { get; set; }
        public int siparisNo { get; set; }
        public int kitapNo { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Siparis Siparis { get; set; }
    }
}
